dubbo:
#  scan:
#    base-packages: com.dubbo.provider.service
  application:
    name: dubbo-provider
    id: dubbo-provider-1
  registry:
    address: 127.0.0.1:2181
    # 读者请自行更改zookeeper地址
    protocol: zookeeper
    check: false
  protocol:
    name: dubbo
    port: 30003
  monitor:
    protocol: register
  provider:
    timeout: 2000
    retries: 1
  consumer:
    check: false
    timeout: 3000
  metadata-report:
    address: zookeeper://127.0.0.1:2181

server:
  port: 8061
